### ISSUE TITLE
Error Install Cartoview Ubuntu 16.04 Geonode 2.6

### ISSUE THREAD

**Issue by dpadron2** [cartologic/cartoview#12]
Hello

First, congratulate them on the launch of the new version of Cartoview.

I have tested:
1.- Install Geonode 2.6 Using Django 1.8.17, using repository in Ubuntu 16.04 sudo add-apt-repository ppa: geonode/testing
2.- I followed the instructions of http://cartologic.github.io/cartoview/#install-on-ubuntu-linux
3.- In the step python manage.py migrate, the following error is generated:

**python manage.py migrate**
Operations to perform:
  Synchronize unmigrated apps: tasks, modeltranslation, cartoview, django_extensions, polymorphic, user_engage, treebeard, gis, pinax_theme_bootstrap_account, django_forms_bootstrap, catalogue, humanize, geoserver, storages, mptt, friendlytagloader, staticfiles, geoexplorer, sitemaps, proxy, pinax_theme_bootstrap, pagination, geonode-client, autocomplete_light, messages, leaflet, api, social, security
  Apply all migrations: dialogos, people, tastypie, app_manager, agon_ratings, documents, actstream, sites, maps, contenttypes, announcements, user_messages, layers, sessions, guardian, auth, base, groups, services, oauth2_provider, account, admin, djcelery, upload, avatar, taggit
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying avatar.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "avatar_avatar" already exists

Any ideas?

Thanks for the help

**Comment by hishamkaram** [comment]
Hello @dpadron2 
try this command `python manage.py --fake avatar_avatar`
