### ISSUE TITLE
Geonode installation error

### ISSUE THREAD

**Issue by NicholasDsouza1996** [cartologic/cartoview#137]
## Please fill the following information to avoid closing issue

_Describe your issue in detail_ 

- Geonode Version : (2.6)
- log (optional):
```
pip install -r requirements.txt

**Output:**
Obtaining geonode from git+git://github.com/GeoNode/geonode.git@master#egg=geonode (from -r requirements.txt (line 1))
  Updating ./Envs/geonode/src/geonode clone (to master)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/ubuntu/Envs/geonode/src/geonode/setup.py", line 33, in <module>
        version=__import__('geonode').get_version(),
      File "geonode/__init__.py", line 25, in <module>
        from .celery import app as celery_app
      File "geonode/celery.py", line 24, in <module>
        from celery import Celery
    ImportError: No module named celery
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/ubuntu/Envs/geonode/src/geonode/

```

**Comment by ahmednoureldeen** [comment]
Just pip install celery first

**Comment by NicholasDsouza1996** [comment]
@ahmednoureldeen 

output: Requirement already satisfied: celery in /usr/lib/python2.7/dist-packages

**Comment by hishamkaram** [comment]
@NicholasDsouza1996 any updates on this issue?

**Comment by fasingagerda** [comment]
Use pip install with --ignored-installes options to reinstalled celer
Pip install celery==(look in ur requirements.txt) --ignored-installed

**Comment by hishamkaram** [comment]
@NicholasDsouza1996 feel free to reopen this issue
