### ISSUE TITLE
Is it possible to use differrent Django version?

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#145]
Try to use Django 1.11.10 but failed.

- Cartoview Version : 1.4.5
- Geonode Version : 2.6.3
- Django Version: 1.11.10
```
(myenv) az@ubuntu:~/sfd$ python manage.py makemigrations app_manager
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in exec                       ute_from_command_line
    utility.execute()
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in exec                       ute
    django.setup()
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/geonode/social/apps.py", line 2, in <module>
    from actstream import registry
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/actstream/registry.py", line 11, in <module>
    from actstream.compat import generic, get_model
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/actstream/compat.py", line 22, in <module>
    from django.contrib.contenttypes import fields as generic
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/contrib/contenttypes/fields.py", line 5, in <mo                       dule>
    from django.contrib.contenttypes.models import ContentType
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 139, in <                       module>
    class ContentType(models.Model):
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 110, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 247, in get_containing_                       app_config
    self.check_apps_ready()
  File "/home/az/.virtualenvs/myenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 125, in check_apps_read                       y
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

```

**Comment by hishamkaram** [comment]
no please use `django==1.8.7`

**Comment by lolob** [comment]
Thanks

**Comment by hishamkaram** [comment]
you are welcome 💯
