### ISSUE TITLE
Error install Cartoview 1.5.7 Ubuntu 16.04

### ISSUE THREAD

**Issue by dpadron** [cartologic/cartoview#146]
## Please fill the following information to avoid closing issue

_Describe your issue in detail_ 

- Cartoview Version : (1.5.7)
- Geonode Version : (2.6.3)
- log (optional):
```
(env) root@idesca:/home/geo/idesca# python manage.py makemigrations app_manager
/home/geo/env/local/lib/python2.7/site-packages/geonode/catalogue/__init__.py:27: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/geo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/geo/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/geo/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/geo/env/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geo/env/local/lib/python2.7/site-packages/geonode/base/models.py", line 56, in <module>
    from geonode.utils import bbox_to_wkt
  File "/home/geo/env/local/lib/python2.7/site-packages/geonode/utils.py", line 31, in <module>
    from slugify import Slugify
  File "/home/geo/env/local/lib/python2.7/site-packages/slugify/__init__.py", line 2, in <module>
    from slugify.main import Slugify, UniqueSlugify
ImportError: No module named main
(env) root@idesca:/home/geo/idesca#

**Comment by hishamkaram** [comment]
Hello @dpadron  
open this file `/home/geo/env/local/lib/python2.7/site-packages/slugify/__init__.py`
and change this line `from slugify.main import Slugify, UniqueSlugify` to `from .main import Slugify, UniqueSlugify`
Thanks

**Comment by dpadron** [comment]
(env) root@idesca:/home/geo/idesca# python manage.py makemigrations app_manager
/home/geo/env/local/lib/python2.7/site-packages/geonode/catalogue/__init__.py:27: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/geo/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/geo/env/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/geo/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/geo/env/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geo/env/local/lib/python2.7/site-packages/geonode/base/models.py", line 56, in <module>
    from geonode.utils import bbox_to_wkt
  File "/home/geo/env/local/lib/python2.7/site-packages/geonode/utils.py", line 31, in <module>
    from slugify import Slugify
  File "/home/geo/env/local/lib/python2.7/site-packages/slugify/__init__.py", line 3, in <module>
    from slugify.alt_translates import *
ImportError: No module named alt_translates
(env) root@idesca:/home/geo/idesca#

**Comment by hishamkaram** [comment]
try this command `pip uninstall awesome-slugify && pip install awesome-slugify==1.6.5 --no-cache-dir `@dpadron

**Comment by hishamkaram** [comment]
apply the following steps in order:
1. `pip uninstall awesome-slugify`
2. `pip uninstall transifex-client`
3. `pip install transifex-client==0.12.5`
4. `pip install awesome-slugify==1.6.5`

**Comment by hishamkaram** [comment]
@dpadron closed due to lake of response, feel free to reopen again
