### ISSUE TITLE
I am facing issue while installing cartoview in docker

### ISSUE THREAD

**Issue by vinayak1411** [cartologic/cartoview#150]
sudo make run
```
# bring up the services
docker-compose up -d
communitygis_postgis_1 is up-to-date
communitygis_elasticsearch_1 is up-to-date
communitygis_rabbitmq_1 is up-to-date
communitygis_nginx_1 is up-to-date
communitygis_geoserver_1 is up-to-date
communitygis_cartoview_1 is up-to-date
sleep 5
docker-compose exec cartoview python manage.py makemigrations app_manager
Error response from daemon: Container 5f5359e0f4912945ee4cf222d5757bae71f7d3372b32b7858e10600990bb31a8 is restarting, wait until the container is running
Makefile:16: recipe for target 'prepare_manager' failed
make: *** [prepare_manager] Error 1
```

**Comment by hishamkaram** [comment]
Hello @vinayak1411  
sorry for being late, please can add docker logs to this issue.
- to get logs use this command : 
`docker-compose logs`

**Comment by vinayak1411** [comment]
$ docker-compose logs
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/compose/cli/command.py", line 41, in project_from_options
    compatibility=options.get('--compatibility'),
  File "/home/ubuntu/.local/lib/python2.7/site-packages/compose/cli/command.py", line 121, in get_project
    host=host, environment=environment
  File "/home/ubuntu/.local/lib/python2.7/site-packages/compose/cli/command.py", line 92, in get_client
    environment=environment, tls_version=get_tls_version(environment)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/compose/cli/docker_client.py", line 120, in docker_client
    client = APIClient(**kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/docker/api/client.py", line 114, in __init__
    base_url, IS_WINDOWS_PLATFORM, tls=bool(tls)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/docker/utils/utils.py", line 279, in parse_host
    "Bind address needs a port: {0}".format(addr))
docker.errors.DockerException: Bind address needs a port: 13.57.199.28

**Comment by hishamkaram** [comment]
@vinayak1411 please post your `docker-compose.yml`

**Comment by hishamkaram** [comment]
@vinayak1411 closed due to lack of response , feel free to reopen this issue again

**Comment by darkn3rd** [comment]
This has nothing to do with the docker-compose.yml.  This is with the docker-compose within the Ubuntu site-packages not functioning correctly.
