### ISSUE TITLE
Installation problems on Ubuntu 16.04 and Geonode 2.8

### ISSUE THREAD

**Issue by mconte79** [cartologic/cartoview#178]
Hi,
  I tried to add cartoview on existing geonode following this instructions:
1) pip install cartoview==1.8.3 --no-cache-dir => OK no errors;
2) open geonode settings.py and add the following lines at the end of the file....I add the lines to the files /usr/local/lib/python2.7/dist-packages/geonode/settings.py
3) reboot

When the server is on if I try to access to Geonode I get Internal Server Error.

In the apache error.log I find this messages:
[Wed Sep 12 14:22:54.488436 2018] [mpm_event:notice] [pid 1420:tid 139792714028928] AH00491: caught SIGTERM, shutting down
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called in the current subinterpreter.  Returning 0.
[Wed Sep 12 14:23:35.842473 2018] [wsgi:warn] [pid 1440:tid 140316488402816] mod_wsgi: Compiled for Python/2.7.11.
[Wed Sep 12 14:23:35.842649 2018] [wsgi:warn] [pid 1440:tid 140316488402816] mod_wsgi: Runtime using Python/2.7.12.
[Wed Sep 12 14:23:35.843643 2018] [mpm_event:notice] [pid 1440:tid 140316488402816] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Wed Sep 12 14:23:35.843674 2018] [core:notice] [pid 1440:tid 140316488402816] AH00094: Command line: '/usr/sbin/apache2'
[Wed Sep 12 07:23:45.464017 2018] [wsgi:error] [pid 1443:tid 140316354684672] [09-12 07:23:45] p1443  { cartoview.app_manager.helpers /usr/local/lib/python2.7/dist-packages/cartoview/app_manager/helpers.py:18}                             ERROR - 
[Wed Sep 12 07:23:45.464193 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754] mod_wsgi (pid=1443): Target WSGI script '/var/www/geonode/wsgi/geonode.wsgi' cannot be loaded as Python module.
[Wed Sep 12 07:23:45.464209 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754] mod_wsgi (pid=1443): Exception occurred processing WSGI script '/var/www/geonode/wsgi/geonode.wsgi'.
[Wed Sep 12 07:23:45.464231 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754] Traceback (most recent call last):
[Wed Sep 12 07:23:45.464251 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/var/www/geonode/wsgi/geonode.wsgi", line 7, in <module>
[Wed Sep 12 07:23:45.464321 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     application = get_wsgi_application()
[Wed Sep 12 07:23:45.464337 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Wed Sep 12 07:23:45.467280 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     django.setup()
[Wed Sep 12 07:23:45.467298 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
[Wed Sep 12 07:23:45.474472 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed Sep 12 07:23:45.474492 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
[Wed Sep 12 07:23:45.479550 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     self._setup(name)
[Wed Sep 12 07:23:45.479569 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
[Wed Sep 12 07:23:45.479592 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     self._wrapped = Settings(settings_module)
[Wed Sep 12 07:23:45.479603 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
[Wed Sep 12 07:23:45.479619 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed Sep 12 07:23:45.479630 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Wed Sep 12 07:23:45.480055 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     __import__(name)
[Wed Sep 12 07:23:45.480073 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/local/lib/python2.7/dist-packages/geonode/settings.py", line 1350, in <module>
[Wed Sep 12 07:23:45.480391 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     INSTALLED_APPS += load_apps()
[Wed Sep 12 07:23:45.480409 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/local/lib/python2.7/dist-packages/cartoview/app_manager/settings.py", line 33, in load_apps
[Wed Sep 12 07:23:45.480594 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     create_apps_dir()
[Wed Sep 12 07:23:45.480611 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/local/lib/python2.7/dist-packages/cartoview/app_manager/settings.py", line 28, in create_apps_dir
[Wed Sep 12 07:23:45.480632 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     change_path_permission(settings.APPS_DIR)
[Wed Sep 12 07:23:45.480644 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]   File "/usr/local/lib/python2.7/dist-packages/cartoview/app_manager/helpers.py", line 25, in change_path_permission
[Wed Sep 12 07:23:45.480818 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754]     os.chmod(path, mode)
[Wed Sep 12 07:23:45.480851 2018] [wsgi:error] [pid 1443:tid 140316354684672] [remote 192.168.0.142:21754] OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/geonode/apps'

How I can resolve?
Best regards
Matteo

**Comment by hishamkaram** [comment]
could you show me these lines you added to your local_settings.py?

**Comment by mconte79** [comment]
Hi @hishamkaram I added these line to settings.py (not local_settings.py):
from cartoview import settings as cartoview_settings


INSTALLED_APPS = cartoview_settings.INSTALLED_APPS
ROOT_URLCONF = cartoview_settings.ROOT_URLCONF


APPS_DIR = os.path.abspath(os.path.join(PROJECT_ROOT, "apps"))
PENDING_APPS = os.path.join(PROJECT_ROOT, "pendingOperation.yml")

# NOTE: please comment the following line of you want to use geonode templates
TEMPLATES[0]["DIRS"] = cartoview_settings.CARTOVIEW_TEMPLATE_DIRS + TEMPLATES[0]["DIRS"]
TEMPLATES[0]["OPTIONS"]['context_processors'] += cartoview_settings.CARTOVIEW_CONTEXT_PROCESSORS


STATICFILES_DIRS += cartoview_settings.CARTOVIEW_STATIC_DIRS


from cartoview.app_manager.settings import load_apps
INSTALLED_APPS += load_apps()
Kind regards
Matteo

**Comment by hishamkaram** [comment]
@mconte79 
how did you installed geonode ?

**Comment by mconte79** [comment]
Hi,
  I followed the instrunctions at the page http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html. Standard deployment for Ubuntu

**Comment by hishamkaram** [comment]
hello @mconte79 sorry for being late
1- add the following lines to settings.py to add cartoview to your geonode 
**note: remove the previous cartoview settings from geonode and add the following lines**
```
from cartoview import settings as cartoview_settings

INSTALLED_APPS = cartoview_settings.INSTALLED_APPS
ROOT_URLCONF = cartoview_settings.ROOT_URLCONF

APPS_DIR = os.path.abspath(os.path.join(PROJECT_ROOT, "apps"))
PENDING_APPS = os.path.join(PROJECT_ROOT, "pendingOperation.yml")

# NOTE: please comment the following line of you want to use geonode templates
TEMPLATES[0][
    "DIRS"] = cartoview_settings.CARTOVIEW_TEMPLATE_DIRS + TEMPLATES[0]["DIRS"]
TEMPLATES[0]["OPTIONS"][
    'context_processors'] += cartoview_settings.CARTOVIEW_CONTEXT_PROCESSORS

STATICFILES_DIRS += cartoview_settings.CARTOVIEW_STATIC_DIRS

from cartoview.app_manager.settings import load_apps
INSTALLED_APPS += load_apps(APPS_DIR)
```
2- clone cartoview from github 
3- cd cartoview folder and type pip install -e .

**Comment by mconte79** [comment]
Hi @hishamkaram I tried with your instructions:
1) In the folder /usr/local/lib/python2.7/dist-packages I clone cartoview from github;
2) I entered in cartoview folder and run "pip install -e ."
3) In setting.py of geonode (/usr/local/lib/python2.7/dist-packages/geonode) I removed the older lines and inserted the new lines.
4) I rebooted the system

When the server is on if I try to access to Geonode I get Internal Server Error. In the apache log I found this errors:

[Mon Sep 17 11:41:37.660985 2018] [wsgi:error] [pid 1442:tid 139698272978688] [09-17 11:41:37] p1442  { cartoview.app_manager.helpers /usr/local/lib/python2.7/dist-packages/cartoview/cartoview/app_manager/helpers.py:18}                             ERROR - 
[Mon Sep 17 11:41:37.661191 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728] mod_wsgi (pid=1442): Target WSGI script '/var/www/geonode/wsgi/geonode.wsgi' cannot be loaded as Python module.
[Mon Sep 17 11:41:37.661207 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728] mod_wsgi (pid=1442): Exception occurred processing WSGI script '/var/www/geonode/wsgi/geonode.wsgi'.
[Mon Sep 17 11:41:37.661231 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728] Traceback (most recent call last):
[Mon Sep 17 11:41:37.661253 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/var/www/geonode/wsgi/geonode.wsgi", line 7, in <module>
[Mon Sep 17 11:41:37.661318 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     application = get_wsgi_application()
[Mon Sep 17 11:41:37.661337 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Mon Sep 17 11:41:37.665780 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     django.setup()
[Mon Sep 17 11:41:37.665803 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 17, in setup
[Mon Sep 17 11:41:37.669704 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Mon Sep 17 11:41:37.669732 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
[Mon Sep 17 11:41:37.674601 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     self._setup(name)
[Mon Sep 17 11:41:37.674625 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
[Mon Sep 17 11:41:37.674652 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     self._wrapped = Settings(settings_module)
[Mon Sep 17 11:41:37.674666 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
[Mon Sep 17 11:41:37.674686 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Mon Sep 17 11:41:37.674699 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Mon Sep 17 11:41:37.675139 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     __import__(name)
[Mon Sep 17 11:41:37.675161 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/local/lib/python2.7/dist-packages/geonode/settings.py", line 1348, in <module>
[Mon Sep 17 11:41:37.675465 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     INSTALLED_APPS += load_apps(APPS_DIR)
[Mon Sep 17 11:41:37.675512 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/local/lib/python2.7/dist-packages/cartoview/cartoview/app_manager/settings.py", line 31, in load_apps
[Mon Sep 17 11:41:37.675580 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     create_apps_dir(APPS_DIR)
[Mon Sep 17 11:41:37.675598 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/local/lib/python2.7/dist-packages/cartoview/cartoview/app_manager/settings.py", line 27, in create_apps_dir
[Mon Sep 17 11:41:37.675620 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     change_path_permission(APPS_DIR)
[Mon Sep 17 11:41:37.675634 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]   File "/usr/local/lib/python2.7/dist-packages/cartoview/cartoview/app_manager/helpers.py", line 25, in change_path_permission
[Mon Sep 17 11:41:37.675695 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728]     os.chmod(path, mode)
[Mon Sep 17 11:41:37.675733 2018] [wsgi:error] [pid 1442:tid 139698272978688] [remote 192.168.0.142:51728] OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/geonode/apps'

**Comment by hishamkaram** [comment]
@mconte79 I think cartoview couldn't create apps folder try to create this folder and change this folder permission to world permission with this command:
`sudo mkdir -p /usr/local/lib/python2.7/dist-packages/geonode/apps && sudo chmod -R 777 /usr/local/lib/python2.7/dist-packages/geonode/apps`

**Comment by mconte79** [comment]
hi @hishamkaram I have created the folder and seted the permission. I get the same problem and in apache log I found this
[Mon Sep 17 09:09:37.790338 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209] mod_wsgi (pid=1437): Target WSGI script '/var/www/geonode/wsgi/geonode.wsgi' cannot be loaded as Python module.
[Mon Sep 17 09:09:37.790401 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209] mod_wsgi (pid=1437): Exception occurred processing WSGI script '/var/www/geonode/wsgi/geonode.wsgi'.
[Mon Sep 17 09:09:37.790433 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209] Traceback (most recent call last):
[Mon Sep 17 09:09:37.790461 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/var/www/geonode/wsgi/geonode.wsgi", line 7, in <module>
[Mon Sep 17 09:09:37.790528 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     application = get_wsgi_application()
[Mon Sep 17 09:09:37.790548 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Mon Sep 17 09:09:37.794156 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     django.setup()
[Mon Sep 17 09:09:37.794180 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
[Mon Sep 17 09:09:37.803106 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     apps.populate(settings.INSTALLED_APPS)
[Mon Sep 17 09:09:37.803131 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
[Mon Sep 17 09:09:37.812140 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     app_config = AppConfig.create(entry)
[Mon Sep 17 09:09:37.812165 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 119, in create
[Mon Sep 17 09:09:37.812425 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     import_module(entry)
[Mon Sep 17 09:09:37.812449 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Mon Sep 17 09:09:37.816352 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     __import__(name)
[Mon Sep 17 09:09:37.816374 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/local/lib/python2.7/dist-packages/geonode/people/__init__.py", line 21, in <module>
[Mon Sep 17 09:09:37.817505 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     from geonode.notifications_helper import NotificationsAppConfigBase
[Mon Sep 17 09:09:37.817526 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/local/lib/python2.7/dist-packages/geonode/notifications_helper.py", line 37, in <module>
[Mon Sep 17 09:09:37.818798 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     notifications = import_module(M)
[Mon Sep 17 09:09:37.818820 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Mon Sep 17 09:09:37.818843 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209]     __import__(name)
[Mon Sep 17 09:09:37.818867 2018] [wsgi:error] [pid 1437:tid 140647449618176] [remote 192.168.0.142:8209] ImportError: No module named notifications

**Comment by mconte79** [comment]
@hishamkaram it should be the last stable release available. Before run apt-get install geonode I run sudo add-apt-repository ppa:geonode/stable.

**Comment by jitendrashahiitb** [comment]
Swapnil ( swapnilp692@gmail.com ) was trying to install cartoview on ubuntu 16.04 as per your youtube video.
PFB:-https://www.youtube.com/watch?v=gpIziNss270

He was almost close to completion but got stuck in the last minute at below error.
Any help would be appreciated.

![cartoview_installation_failure](https://user-images.githubusercontent.com/4946297/51955019-51422980-2468-11e9-9164-8b412b6d024b.png)

**Comment by khaledboka** [comment]
@jitendrashahiitb
Hello,
 Would you please use the latest Makefile, where the bower commands are now deprecated and Cartoview included only the required static files

Try to replace Makefile inside the project folder, then run the command 
$ make run


https://github.com/cartologic/cartoview/blob/master/Makefile

**Comment by LazySwap** [comment]
Cartoview -1.8.5 Installation Pip failed on Ubuntu 16.04 with Geonode-2.8rc11

Got error during executing following command - pip install cartoview==1.8.5 --no-cache-dir

![cartov](https://user-images.githubusercontent.com/22761572/52035461-9c376c00-2550-11e9-9f9e-bf753cf3b739.png)

**Comment by jitendrashahiitb** [comment]
@mconte79 @hishamkaram Can we get help?
@LazySwap has posted our issue a few days back.
Hoping to sort this early if possible.

**Comment by hishamkaram** [comment]
@jitendrashahiitb  how do you install cartoview?

**Comment by hishamkaram** [comment]
@LazySwap which version of python you are using?

**Comment by LazySwap** [comment]
Installing cartoview by:-  pip install cartoview==1.8.5 --no-cache-dir

Python -2.7

**Comment by LazySwap** [comment]
Any update @hishamkaram ?

**Comment by hishamkaram** [comment]
@LazySwap this error is related to gsconfig package please post this issue [here](https://github.com/boundlessgeo/gsconfig/issues)

**Comment by jitendrashahiitb** [comment]
Any help ? @LazySwap has posted the issue.
