### ISSUE TITLE
cartoview not working with elastic search

### ISSUE THREAD

**Issue by hishamkaram** [cartologic/cartoview#192]
cartoview not working with elastic search

- Cartoview Version : (1.10.x,1.8.x)
- Geonode Version : (2.10.x,2.8.x)
- log (optional):
```
cartoview-cartoview_play | NoReverseMatch: Reverse for 'api_get_search' with keyword arguments '{u'api_name': u'api', u'resource_name': u'appinstances'}' not found. 12 pattern(s) tried: [u'(?P<api_name>api)/(?P<resource_name>profiles)/search/$', u'(?P<api_name>api)/(?P<resource_name>maps)/search/$', u'(?P<api_name>api)/(?P<resource_name>layers)/search/$', u'(?P<api_name>api)/(?P<resource_name>featured)/search/$', u'(?P<api_name>api)/(?P<resource_name>documents)/search/$', u'(?P<api_name>api)/(?P<resource_name>base)/search/$', u'(?P<api_name>api)/(?P<resource_name>profiles)/search/$', u'(?P<api_name>api)/(?P<resource_name>maps)/search/$', u'(?P<api_name>api)/(?P<resource_name>layers)/search/$', u'(?P<api_name>api)/(?P<resource_name>featured)/search/$', u'(?P<api_name>api)/(?P<resource_name>documents)/search/$', u'(?P<api_name>api)/(?P<resource_name>base)/search/$']
cartoview-cartoview_play | ERROR 2019-01-26 17:34:02,450 exception 1 140610484811520 Internal Server Error: /apps/appinstances/
cartoview-cartoview_play | Traceback (most recent call last):
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
cartoview-cartoview_play |     response = get_response(request)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
cartoview-cartoview_play |     response = self._get_response(request)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
cartoview-cartoview_play |     response = self.process_exception_by_middleware(e, request)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
cartoview-cartoview_play |     response = response.render()
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 107, in render
cartoview-cartoview_play |     self.content = self.rendered_content
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/response.py", line 84, in rendered_content
cartoview-cartoview_play |     content = template.render(context, self._request)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
cartoview-cartoview_play |     return self.template.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 207, in render
cartoview-cartoview_play |     return self._render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
cartoview-cartoview_play |     return self.nodelist.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
cartoview-cartoview_play |     bit = node.render_annotated(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
cartoview-cartoview_play |     return self.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
cartoview-cartoview_play |     return compiled_parent._render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
cartoview-cartoview_play |     return self.nodelist.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
cartoview-cartoview_play |     bit = node.render_annotated(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
cartoview-cartoview_play |     return self.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
cartoview-cartoview_play |     return compiled_parent._render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
cartoview-cartoview_play |     return self.nodelist.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
cartoview-cartoview_play |     bit = node.render_annotated(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
cartoview-cartoview_play |     return self.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
cartoview-cartoview_play |     return compiled_parent._render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
cartoview-cartoview_play |     return self.nodelist.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
cartoview-cartoview_play |     bit = node.render_annotated(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
cartoview-cartoview_play |     return self.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
cartoview-cartoview_play |     result = block.nodelist.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
cartoview-cartoview_play |     bit = node.render_annotated(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
cartoview-cartoview_play |     return self.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 322, in render
cartoview-cartoview_play |     return nodelist.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 990, in render
cartoview-cartoview_play |     bit = node.render_annotated(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
cartoview-cartoview_play |     return self.render(context)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 458, in render
cartoview-cartoview_play |     url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
cartoview-cartoview_play |     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
cartoview-cartoview_play |   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
cartoview-cartoview_play |     raise NoReverseMatch(msg)
cartoview-cartoview_play | NoReverseMatch: Reverse for 'api_get_search' with keyword arguments '{u'api_name': u'api', u'resource_name': u'appinstances'}' not found. 12 pattern(s) tried: [u'(?P<api_name>api)/(?P<resource_name>profiles)/search/$', u'(?P<api_name>api)/(?P<resource_name>maps)/search/$', u'(?P<api_name>api)/(?P<resource_name>layers)/search/$', u'(?P<api_name>api)/(?P<resource_name>featured)/search/$', u'(?P<api_name>api)/(?P<resource_name>documents)/search/$', u'(?P<api_name>api)/(?P<resource_name>base)/search/$', u'(?P<api_name>api)/(?P<resource_name>profiles)/search/$', u'(?P<api_name>api)/(?P<resource_name>maps)/search/$', u'(?P<api_name>api)/(?P<resource_name>layers)/search/$', u'(?P<api_name>api)/(?P<resource_name>featured)/search/$', u'(?P<api_name>api)/(?P<resource_name>documents)/search/$', u'(?P<api_name>api)/(?P<resource_name>base)/search/$']

```
![screen shot 2019-01-26 at 7 34 45 pm](https://user-images.githubusercontent.com/24391550/51790732-c16b5980-21a1-11e9-85a0-962795df5adf.png)

**Comment by hishamkaram** [comment]
fixed https://github.com/cartologic/cartoview/pull/188/commits/1aadbe303dd76df721f9239c0f38de5efd85ae60
