### ISSUE TITLE
Cartoview settings don't work in local_settings.py

### ISSUE THREAD

**Issue by ibrahimawadhamid** [cartologic/cartoview#193]
## Please fill the following information to avoid closing issue
If you put Cartoview settings in local_settings.py, it produces the attached error. Settings must be put in settings.py to work.

- Cartoview Version : (1.10.x)
- Geonode Version : (2.10rc4)
- log:
```
No module named local_settings
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/iawad/geonode/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/iawad/geonode/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/home/iawad/geonode/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/iawad/geonode/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/iawad/geonode/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/iawad/geonode/geonode/settings.py", line 1709, in <module>
    from local_settings import *
  File "/home/iawad/geonode/geonode/local_settings.py", line 594, in <module>
    load_apps(APPS_DIR)
  File "/home/iawad/cartoview/cartoview/app_manager/settings.py", line 26, in load_apps
    from cartoview.apps_handler.utils import create_apps_dir
  File "/home/iawad/cartoview/cartoview/apps_handler/__init__.py", line 3, in <module>
    create_apps_dir()
  File "/home/iawad/cartoview/cartoview/apps_handler/utils.py", line 18, in create_apps_dir
    project_dir = getattr(settings, 'BASE_DIR', settings.PROJECT_DIR)
  File "/home/iawad/geonode/venv/local/lib/python2.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'PROJECT_DIR'

```

**Comment by ibrahimawadhamid** [comment]
I solved the issue.
I imported the local_settings at the start of the settings.py instead of the end of it.
