### ISSUE TITLE
Error after installing Apps from Geo App Market

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#54]
Hi,

I don't understand these errors; I installed a few apps as below
1) cartoview_map_viewer
2) cartoview_feature_list
3) cartoview_charts_viewer
4) cartoview_summary_viewer
5) cartoview_collector
6)  cartoview_webapp_builder
7)  cartoview_dashboard
8)  cartoview_time_data_viewer
9)  cartoview_buffer_tool

"(arsm_app) kiki@ubuntu:~/sam_v1$ python manage.py runserver 192.168.221.130:8000
Performing system checks...
System check identified some issues:
WARNINGS:
base.ResourceBase.tkeywords: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
August 12, 2017 - 08:04:53
Django version 1.8.18, using settings 'sam_v1.settings'
Starting development server at http://192.168.221.130:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63,            in __call__
    return self.application(environ, start_response)
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call           __
    self.load_middleware()
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_pat           terns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf           _module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/cartoview/urls.py", line 17, in <module>
    (r'^apps/', include('cartoview.app_manager.urls')),
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/cartoview/app_manager/urls.py", line 94, in <module>
    urlpatterns.append(app_url(app_config.name))
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/cartoview/app_manager/urls.py", line 85, in app_url
    include('%s.urls' % app),
  File "/home/kiki/.virtualenvs/arsm_app/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kiki/sam_v1/apps/cartoview_collector/urls.py", line 2, in <module>
    import views
  File "/home/kiki/sam_v1/apps/cartoview_collector/views.py", line 6, in <module>
    from cartoview_feature_list.viewer_widgets import widgets as feature_list_widgets
ImportError: No module named viewer_widgets "

How to manually uninstall the apps?
Thanks.

**Comment by hishamkaram** [comment]
for now you can fix this error by removing `cartoview_collector` from apps folder and remove it record from `apps.yml` file and restart server then goto you admin panel under app_manager section open `Apps` and remove `collector App` .

**we are working on a new version of this app , the new version will be available on App Market soon**
