### ISSUE TITLE
ImportError: cannot import name ReadingError

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#57]
Hi,

I got this error 'ImportError: cannot import name ReadingError' 

```
(arsm) kiki@ubuntu:~/onemap$ python manage.py runserver 192.168.221.130:8000
Performing system checks...

System check identified some issues:

WARNINGS:
base.ResourceBase.tkeywords: (fields.W340) null has no effect on ManyToManyField.

System check identified 1 issue (0 silenced).
August 26, 2017 - 20:12:20
Django version 1.8.18, using settings 'onemap.settings'
Starting development server at http://192.168.221.130:8000/
Quit the server with CONTROL-C.

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __cal      l__
    return self.application(environ, start_response)
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/cartoview/urls.py", line 2, in <module>
    from geonode.urls import urlpatterns
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/geonode/urls.py", line 66, in <module>
    (r'^catalogue/', include('geonode.catalogue.urls')),
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/geonode/catalogue/urls.py", line 22, in <module>
    from . import views
  File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/geonode/catalogue/views.py", line 29, in <module>
    from geonode.catalogue.backends.pycsw_local import CONFIGURATION
  'File "/home/kiki/.virtualenvs/arsm/local/lib/python2.7/site-packages/geonode/catalogue/backends/pycsw_local.py", line 29, in <m      odule>
    from shapely.geometry.base import ReadingError'
'ImportError: cannot import name ReadingError'

[26/Aug/2017 20:12:31] "GET / HTTP/1.1" 500 59
```

**Comment by hishamkaram** [comment]
hello @lolob 
if you are not using docker you can fix this error by installing Shapely1.5.17 using this command:
`pip install Shapely==1.5.17`
if you are using docker you can pull the  new docker image using this command:
`docker-compose pull cartoview`
note: restart server in both cases
