### ISSUE TITLE
NameError: global name 'log' is not defined

### ISSUE THREAD

**Issue by lolob** [cartologic/cartoview#58]
Hi again,
Thanks for the previous reply.
There is another one, apps will install fine except small error below; Happens  to all apps during installation. I just ignore them.

```
[27/Aug/2017 01:00:04] "POST /apps/install/1/cartoview_dashboard/latest/ HTTP/1.1" 200 33
Exception in thread Thread-192:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run self.function(*self.args, **self.kwargs)
  File "/home/azzams/.virtualenvs/arsm/local/lib/python2.7/site-packages/cartoview/app_manager/installer.py", line 204, in _finalize_setup                
    stdout=log,
NameError: global name 'log' is not defined
```

**Comment by hishamkaram** [comment]
fixed https://github.com/cartologic/cartoview/commit/047c4f55d14562c92f547dfb141749d77a1ed47e

**Comment by hishamkaram** [comment]
please install latest version : 
pip install cartoview==1.2.68
