### ISSUE TITLE
Installing Cartoview and no apps

### ISSUE THREAD

**Issue by webturtles** [cartologic/cartoview#60]
Hi 

Installed the current stable GeoNode release (all working) and followed instructions on [github.io](http://cartologic.github.io/installation_windows/) to install Cartoview.  

When running `python manage.py collectstatic --noinput` towards the end I get the following:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\core\management\__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\core\management\__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\core\management\base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\core\management\base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 168, in handle
    collected = self.collect()
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 98, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\contrib\staticfiles\finders.py", line 112, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\contrib\staticfiles\utils.py", line 28, in get_files
    directories, files = storage.listdir(location)
  File "C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\django\core\files\storage.py", line 299, in listdir
    for entry in os.listdir(path):
WindowsError: [Error 3] The system cannot find the path specified: u'C:\\GeoNode-2.6.x\\geonode-2.6.x\\cartoweb\\cartoweb\\static\\*.*'
```

Is this an issue....?

When going to the apps page and clicking manage apps, nothing loads and there are a few 404s.

```
Starting development server at http://0.0.0.0:8000/
Quit the server with CTRL-BREAK.
[01/Sep/2017 13:06:51] "GET /apps HTTP/1.1" 301 0
[01/Sep/2017 13:06:52] "GET /apps/ HTTP/1.1" 200 4957
[01/Sep/2017 13:06:52] "GET /static/cartoview/css/custom.css HTTP/1.1" 304 0
[01/Sep/2017 13:06:53] "GET /static/app_manager/apps_list.css HTTP/1.1" 304 0
[01/Sep/2017 13:06:53] "GET /static/vendor/angular-img-fallback/angular.dcb-img-fallback.min.js HTTP/1.1" 304 0
[01/Sep/2017 13:06:53] "GET /jsi18n/ HTTP/1.1" 200 3014
[01/Sep/2017 13:06:53] "GET /static/cartoview/img/cartoview-logo-text-white.png HTTP/1.1" 304 0
[01/Sep/2017 13:06:53] "GET /lang.js HTTP/1.1" 200 2300
[09-01 13:06:56] p5560  { cartoview.app_manager.views C:\GeoNode-2.6.x\geonode-2.6.x\lib\site-packages\cartoview\app_manager\views.py:100}                               WARNING - []
[01/Sep/2017 13:06:56] "GET /apps/manage/ HTTP/1.1" 200 6108
[01/Sep/2017 13:06:56] "GET /static/app_manager/css/manager.css HTTP/1.1" 304 0
[01/Sep/2017 13:06:56] "GET /static/vendor/angular/angular.min.js HTTP/1.1" 404 1814
[01/Sep/2017 13:06:56] "GET /static/vendor/angular-aria/angular-aria.min.js HTTP/1.1" 404 1844
[01/Sep/2017 13:06:56] "GET /static/vendor/angular-animate/angular-animate.min.js HTTP/1.1" 404 1862
[01/Sep/2017 13:06:56] "GET /jsi18n/ HTTP/1.1" 200 3014
[01/Sep/2017 13:06:56] "GET /static/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js HTTP/1.1" 404 1874
[01/Sep/2017 13:06:57] "GET /static/vendor/angular-resource/angular-resource.min.js HTTP/1.1" 404 1868
[01/Sep/2017 13:06:58] "GET /static/vendor/angular-drag-and-drop-lists/angular-drag-and-drop-lists.min.js HTTP/1.1" 404 1934
[01/Sep/2017 13:06:58] "GET /check-version/ HTTP/1.1" 200 296
[01/Sep/2017 13:06:58] "GET /static/app_manager/js/resources.js HTTP/1.1" 304 0
[01/Sep/2017 13:06:58] "GET /static/app_manager/js/manager.js HTTP/1.1" 304 0
[01/Sep/2017 13:06:58] "GET /lang.js HTTP/1.1" 200 2300
[01/Sep/2017 13:06:58] "GET /static/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js HTTP/1.1" 404 1874
[01/Sep/2017 13:06:58] "GET /static/vendor/angular-animate/angular-animate.min.js HTTP/1.1" 404 1862
[01/Sep/2017 13:06:58] "GET /static/vendor/angular-aria/angular-aria.min.js HTTP/1.1" 404 1844
[01/Sep/2017 13:06:59] "GET /static/vendor/angular-resource/angular-resource.min.js HTTP/1.1" 404 1868
[01/Sep/2017 13:06:59] "GET /static/vendor/angular-drag-and-drop-lists/angular-drag-and-drop-lists.min.js HTTP/1.1" 404 1934

```
Apart from getting at the apps, what is the next step for bedding this in on port 80 with the main GeoNode site?

Thanks
Chris

**Comment by lolob** [comment]
@webturtles My guess, I think you need to have nodejs and bower install.

**Comment by webturtles** [comment]
Thanks, should have said I am on Windows 2016.  Noticed those instructions under Ubuntu, but assumed not required for Windows....

**Comment by lolob** [comment]
I think the instruction is meant to use docker in windows.

**Comment by webturtles** [comment]
Sorry not using Docker, as eventual prod env will be Windows 2012.  Looking to run a dev install (Geonode and Cartoview) on a clean Azure vm for now.

**Comment by ahmednosman** [comment]
@webturtles windows installer is coming soon, please send email at info@cartologic.com and we will send you an early release

**Comment by hishamkaram** [comment]
closed due to lack of response
