### ISSUE TITLE
Tried to make a GET request to http://localhost:8080/geoserver/rest/workspaces/default.xml but got a 404 status code:

### ISSUE THREAD

**Issue by jeffindevasia02** [cartologic/cartoview#9]
get this error when i try to upload a layer or create a map...need help?
also why cant i see apps to deploy ?
are there no apps in market?

**Comment by kamalhg** [comment]
it seems that you don't have geoserver installed on port 8080

you can download apps from http://cartologic.com/cartoview/apps/ but these apps is compatable with cartoview for windows 
you can download from http://cartologic.com/cartoview/download/

**Comment by kamalseisy** [comment]
it seems that you don't have geoserver installed on port 8080

you can download apps from http://cartologic.com/cartoview/apps/ but these apps is compatable with cartoview for windows 
you can download from http://cartologic.com/cartoview/download/

**Comment by jeffindevasia02** [comment]
I do have geoserver installed.. it automatically gets installed   by sudo
paver setup .. right?
I followed your instructions thoroughly

**Comment by kamalseisy** [comment]
yes
try to run `paver start_geoserver` to start geoserver and ensure that it is installed

**Comment by jeffindevasia02** [comment]
sudo paver start_geoserver
[sudo] password for jeffin: 
---> pavement.start_geoserver
cd /home/geonode/geonode/geoserver/data
java -version
java version "1.7.0_121"
OpenJDK Runtime Environment (IcedTea 2.6.8) (7u121-2.6.8-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.121-b00, mixed mode)
java -Xmx512m -XX:MaxPermSize=256m -DGEOSERVER_DATA_DIR=/home/geonode/geonode/geoserver/data -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar /home/geonode/geonode/downloaded/jetty-runner-8.1.8.v20121106.jar --port 8080 --log /home/geonode/geonode/geoserver/jetty.log /home/geonode/geonode/scripts/misc/jetty-runner.xml > /dev/null &
cd /home/geonode/geonode
Starting GeoServer on http://localhost:8080/geoserver/
2017-01-24 14:55:28.162:INFO:omjr.Runner:Runner
2017-01-24 14:55:28.163:WARN:omjr.Runner:No tx manager found
2017-01-24 14:55:28.410:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2017-01-24 14:55:32.671:WARN:oejw.WebAppContext:Failed startup of context o.e.j.w.WebAppContext{/geoserver,file:/home/geonode/geonode/geoserver/geoserver/},../geoserver
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:367)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1248)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:492)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:277)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.runner.Runner.run(Runner.java:504)
	at org.mortbay.jetty.runner.Runner.main(Runner.java:625)
Caused by: 
java.lang.UnsupportedClassVersionError: org/geoserver/GeoserverInitStartupListener : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:421)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at org.eclipse.jetty.server.handler.ContextHandler.loadClass(ContextHandler.java:1514)
	at org.eclipse.jetty.webapp.StandardDescriptorProcessor.visitListener(StandardDescriptorProcessor.java:1864)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.visit(IterativeDescriptorProcessor.java:85)
	at org.eclipse.jetty.webapp.IterativeDescriptorProcessor.process(IterativeDescriptorProcessor.java:72)
	at org.eclipse.jetty.webapp.MetaData.resolve(MetaData.java:367)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1248)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:492)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:172)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
	at org.eclipse.jetty.server.Server.doStart(Server.java:277)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.runner.Runner.run(Runner.java:504)
	at org.mortbay.jetty.runner.Runner.main(Runner.java:625)
2017-01-24 14:55:32.690:INFO:oejs.NCSARequestLog:Opened /home/geonode/geonode/geoserver/jetty.log
2017-01-24 14:55:32.742:WARN:oejuc.AbstractLifeCycle:FAILED SelectChannelConnector@0.0.0.0:8080: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.Server.doStart(Server.java:288)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.runner.Runner.run(Runner.java:504)
	at org.mortbay.jetty.runner.Runner.main(Runner.java:625)
2017-01-24 14:55:32.743:WARN:oejuc.AbstractLifeCycle:FAILED org.eclipse.jetty.server.Server@55ebc96b: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.Server.doStart(Server.java:288)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.runner.Runner.run(Runner.java:504)
	at org.mortbay.jetty.runner.Runner.main(Runner.java:625)
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:463)
	at sun.nio.ch.Net.bind(Net.java:455)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
	at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.eclipse.jetty.server.Server.doStart(Server.java:288)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
	at org.mortbay.jetty.runner.Runner.run(Runner.java:504)
	at org.mortbay.jetty.runner.Runner.main(Runner.java:625)
Usage: java [-DDEBUG] [-Djetty.home=dir] -jar jetty-runner.jar [--help|--version] [ server opts] [[ context opts] context ...] 
Server Options:
 --version                          - display version and exit
 --log file                         - request log filename (with optional 'yyyy_mm_dd' wildcard
 --out file                         - info/warn/debug log filename (with optional 'yyyy_mm_dd' wildcard
 --port n                           - port to listen on (default 8080)
 --stop-port n                      - port to listen for stop command
 --stop-key n                       - security string for stop command (required if --stop-port is present)
 --jar file                         - a jar to be added to the classloader
 --jdbc classname properties jndiname - classname of XADataSource or driver; properties string; name to register in jndi
 --lib dir                          - a directory of jars to be added to the classloader
 --classes dir                      - a directory of classes to be added to the classloader
 --txFile                           - override properties file for Atomikos
 --stats [unsecure|realm.properties] - enable stats gathering servlet context
 --config file                      - a jetty xml config file to use instead of command line options
Context Options:
 --path /path       - context path (default /)
 context            - WAR file, web app dir or context.xml file

**Comment by jeffindevasia02** [comment]
this is what i get when i run the command

**Comment by hishamkaram** [comment]
what is geoserver version?

**Comment by jeffindevasia02** [comment]
paver 1.2.4

**Comment by hishamkaram** [comment]
@jeffindevasia02  i will update installation  instructions today

**Comment by hishamkaram** [comment]
@jeffindevasia02  
remove geonode folder and install geonode by following instruction in this [repo](https://github.com/GeoNode/geonode) the clone cartoview and run server

**Comment by jeffindevasia02** [comment]
sorry didnt get you.. can you elaborate?

**Comment by hishamkaram** [comment]
now you can Follow new Instructions
